---
- name: "Check if an organization {{ item.name }} exists "
  uri:
    url: "{{ gitea_server_root_url }}/api/v1/orgs/{{ item.name }}?token={{ gitea_service_token }}"
    return_content: true
    method: GET
    status_code:
      - 200
      - 404
  register: exists_organization

- name: "Create an organization {{ item.name }} via API"
  uri:
    url: "{{ gitea_server_root_url }}/api/v1/orgs?token={{ gitea_service_token }}"
    return_content: true
    method: POST
    body: { "description": "{{ item.description }}", "full_name": "{{ item.name }}", "location": "{{ item.name }}", "repo_admin_change_team_access": true, "username": "{{ item.name }}", "visibility": "{{ item.visibility }}", "website": "{{ item.name }}" }
    body_format: json
    status_code:
      - 201
      - 422
  register: created_organization
  changed_when: created_organization.status == 201
  when: "exists_organization.json.username is not defined"
