---
# defaults file for postgresql
postgresql:
postgresql_version: "12"
postgresql_service_user: postgres
postgresql_service_group: postgres
postgresql_admin_user: adminuser
postgresql_admin_password: adminpass
postgresql_pg_hba:
  - type: local
    database: all
    user: postgres
    address: ""
    method: peer
  - type: host
    database: gitea
    user: gitea
    address: "::1/128"
    method: md5
  - type: host
    database: gitea
    user: gitea
    address: "127.0.0.1/32"
    method: md5

postgresql_users: []
# - name: gitea
#   password: password12345

postgresql_databases: []
# - name: gitea
#   owner: gitea
